// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlfTQc6ticwYPQaXzbdZA8dm92wk1gCt8',
    appId: '1:699144063175:web:0400ce36b3bfb8ee6f56e2',
    messagingSenderId: '699144063175',
    projectId: 'cefops',
    authDomain: 'cefops.firebaseapp.com',
    databaseURL: 'https://cefops-default-rtdb.firebaseio.com',
    storageBucket: 'cefops.appspot.com',
    measurementId: 'G-CCSWMVMQC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-roYik3QzwjZl9Kf7r-IdbDLJ1PT3WR4',
    appId: '1:699144063175:android:466fef19ca02073d6f56e2',
    messagingSenderId: '699144063175',
    projectId: 'cefops',
    databaseURL: 'https://cefops-default-rtdb.firebaseio.com',
    storageBucket: 'cefops.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFzlOBOam0PQSMrTcct76CnEgn2_6dLKk',
    appId: '1:699144063175:ios:8a62be102ffa91676f56e2',
    messagingSenderId: '699144063175',
    projectId: 'cefops',
    databaseURL: 'https://cefops-default-rtdb.firebaseio.com',
    storageBucket: 'cefops.appspot.com',
    androidClientId: '699144063175-a0adt09u6vlu5aof7ha248i5qk5plll3.apps.googleusercontent.com',
    iosClientId: '699144063175-m8kdjuh0g7lkr20i4sfihiopjamt0gj6.apps.googleusercontent.com',
    iosBundleId: 'com.cefops.cefops.material',
  );
}
